### PR TITLE
predeclare global used in extension

### LINKED ISSUE #210: In Julia 1.10, NLoptMathOptInterfaceExt errors on load
While loading NLopt in Julia 1.10, I got this error:

```
│  ┌ Error: Error during loading of extension NLoptMathOptInterfaceExt of NLopt, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack:
│  │    InitError: Creating a new global in closed module `NLopt` (`Optimizer`) breaks incremental compilation because the side effects will not be permanent.
│  │    Stacktrace:
│  │      [1] __init__()
│  │        @ NLoptMathOptInterfaceExt ~/.julia/packages/NLopt/1EJXl/ext/NLoptMathOptInterfaceExt.jl:17
│  │      [2] run_module_init(mod::Module, i::Int64)
│  │        @ Base ./loading.jl:1128
│  │      [3] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
│  │        @ Base ./loading.jl:1116
│  │      [4] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
│  │        @ Base ./loading.jl:1061
│  │      [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
│  │        @ Base ./loading.jl:1575
│  │      [6] _require(pkg::Base.PkgId, env::Nothing)
│  │        @ Base ./loading.jl:1932
│  │      [7] __require_prelocked(uuidkey::Base.PkgId, env::Nothing)
│  │        @ Base ./loading.jl:1806
│  │      [8] #invoke_in_world#3
│  │        @ Base ./essentials.jl:921 [inlined]
│  │      [9] invoke_in_world
│  │        @ Base ./essentials.jl:918 [inlined]
│  │     [10] _require_prelocked
│  │        @ Base ./loading.jl:1797 [inlined]
│  │     [11] _require_prelocked
│  │        @ Base ./loading.jl:1796 [inlined]
│  │     [12] run_extension_callbacks(extid::Base.ExtensionId)
│  │        @ Base ./loading.jl:1289
│  │     [13] run_extension_callbacks(pkgid::Base.PkgId)
│  │        @ Base ./loading.jl:1324
│  │     [14] run_package_callbacks(modkey::Base.PkgId)
│  │        @ Base ./loading.jl:1158
│  │     [15] _tryrequire_from_serialized(modkey::Base.PkgId, path::String, ocachepath::String, sourcepath::String, depmods::Vector{Any})
│  │        @ Base ./loading.jl:1481
│  │     [16] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
│  │        @ Base ./loading.jl:1568
│  │     [17] _require(pkg::Base.PkgId, env::String)
│  │        @ Base ./loading.jl:1932
│  │     [18] __require_prelocked(uuidkey::Base.PkgId, env::String)
│  │        @ Base ./loading.jl:1806
│  │     [19] #invoke_in_world#3
│  │        @ Base ./essentials.jl:921 [inlined]
│  │     [20] invoke_in_world
│  │        @ Base ./essentials.jl:918 [inlined]
│  │     [21] _require_prelocked(uuidkey::Base.PkgId, env::String)
│  │        @ Base ./loading.jl:1797
│  │     [22] macro expansion
│  │        @ Base ./loading.jl:1784 [inlined]
│  │     [23] macro expansion
│  │        @ Base ./lock.jl:267 [inlined]
│  │     [24] __require(into::Module, mod::Symbol)
│  │        @ Base ./loading.jl:1747
│  │     [25] #invoke_in_world#3
│  │        @ Base ./essentials.jl:921 [inlined]
│  │     [26] invoke_in_world
│  │        @ Base ./essentials.jl:918 [inlined]
│  │     [27] require(into::Module, mod::Symbol)
│  │        @ Base ./loading.jl:1740
│  │     [28] include(mod::Module, _path::String)
│  │        @ Base ./Base.jl:495
│  │     [29] include(x::String)
│  │        @ SingleMoleculeLocalization ~/.julia/packages/SingleMoleculeLocalization/7FZ8u/src/SingleMoleculeLocalization.jl:1
│  │     [30] top-level scope
│  │        @ ~/.julia/packages/SingleMoleculeLocalization/7FZ8u/src/SingleMoleculeLocalization.jl:17
│  │     [31] include
│  │        @ Base ./Base.jl:495 [inlined]
│  │     [32] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
│  │        @ Base ./loading.jl:2216
│  │     [33] top-level scope
│  │        @ stdin:3
│  │     [34] eval
│  │        @ Core ./boot.jl:385 [inlined]
│  │     [35] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│  │        @ Base ./loading.jl:2070
│  │     [36] include_string
│  │        @ Base ./loading.jl:2080 [inlined]
│  │     [37] exec_options(opts::Base.JLOptions)
│  │        @ Base ./client.jl:316
│  │     [38] _start()
│  │        @ Base ./client.jl:552
│  │    during initialization of module NLoptMathOptInterfaceExt
│  └ @ Base loading.jl:1295
```

### PR DESCRIPTION
**Pull request by palday**
potentially fixes #210

### CODE REVIEW

**Comment by ericphanson** [comment]
this is the same as https://github.com/JuliaOpt/NLopt.jl/pull/206 fyi

**Comment by palday** [comment]
Looking at the comments in #206, I saw that there were some thoughts on the impact of a non-const global. I think that issue existed even before now, but we can add a type-annotation to the global (all Julia versions which support extensions also support type annotations on globals), which will reduce some of the impact there.

File: src/NLopt.jl [hunk 1]
```diff
@@ -630,10 +630,14 @@ end
...
 
-if !isdefined(Base, :get_extension)
+@static if !isdefined(Base, :get_extension)
     include("../ext/NLoptMathOptInterfaceExt.jl")
     using .NLoptMathOptInterfaceExt
     const Optimizer = NLoptMathOptInterfaceExt.Optimizer
+else
+    # declare this upfront so that the MathOptInterface extension can assign it
+    # without creating a new global
+    global Optimizer::DataType
```
Comment (stevengj) [inline src/NLopt.jl:640]: This type declaration doesn't really help with anything because it is an abstract type; it's not much better than the default `::Any`.

**Comment by montyvesselinov** [comment]
are you going to merge and release a new version?

File: src/NLopt.jl (hunk 1 above)
Comment (stevengj) [inline src/NLopt.jl:640]:
```suggestion
    global Optimizer```

**Comment by stevengj** [comment]
Thanks for the reminder: https://github.com/JuliaRegistries/General/pull/98576

**Comment by bclyons12** [comment]
@stevengj Just FYI, looks like the the new release version got hung up and won't be released automatically.

**Comment by stevengj** [comment]
https://github.com/JuliaRegistries/General/pull/98655
